ALTER TABLE `questionTemplates` MODIFY COLUMN `equipmentType` enum('refrigerator','auto-refrigerator','chamber','warehouse','other') NOT NULL DEFAULT 'refrigerator';--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'iq', 10, 'Идентифицируется ли холодильная камера и холодильная установка бирками (модель/серийный номер)?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'iq' AND `equipmentType` = 'chamber' AND `text` = 'Идентифицируется ли холодильная камера и холодильная установка бирками (модель/серийный номер)?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'iq', 20, 'Имеются ли инструкции и руководства по эксплуатации холодильной камеры и холодильной установки?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'iq' AND `equipmentType` = 'chamber' AND `text` = 'Имеются ли инструкции и руководства по эксплуатации холодильной камеры и холодильной установки?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'iq', 30, 'Соответствуют ли модель и производитель холодильной установки данным в документации?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'iq' AND `equipmentType` = 'chamber' AND `text` = 'Соответствуют ли модель и производитель холодильной установки данным в документации?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'iq', 40, 'Соответствуют ли место установки и конструкция холодильной камеры проектной документации?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'iq' AND `equipmentType` = 'chamber' AND `text` = 'Соответствуют ли место установки и конструкция холодильной камеры проектной документации?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'iq', 50, 'Подключена ли холодильная установка к электросети согласно требованиям производителя?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'iq' AND `equipmentType` = 'chamber' AND `text` = 'Подключена ли холодильная установка к электросети согласно требованиям производителя?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'iq', 60, 'Предусмотрено ли резервное электропитание холодильной установки (если требуется)?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'iq' AND `equipmentType` = 'chamber' AND `text` = 'Предусмотрено ли резервное электропитание холодильной установки (если требуется)?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'iq', 70, 'Установлены ли средства мониторинга температуры и аварийной сигнализации?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'iq' AND `equipmentType` = 'chamber' AND `text` = 'Установлены ли средства мониторинга температуры и аварийной сигнализации?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'iq', 80, 'Отсутствуют ли видимые повреждения панелей, пола, потолка, двери и уплотнителей камеры?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'iq' AND `equipmentType` = 'chamber' AND `text` = 'Отсутствуют ли видимые повреждения панелей, пола, потолка, двери и уплотнителей камеры?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'iq', 90, 'Закрывается ли дверь камеры плотно и обеспечено ли безопасное открывание изнутри?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'iq' AND `equipmentType` = 'chamber' AND `text` = 'Закрывается ли дверь камеры плотно и обеспечено ли безопасное открывание изнутри?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'oq', 10, 'Запускается ли холодильная установка камеры корректно?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'oq' AND `equipmentType` = 'chamber' AND `text` = 'Запускается ли холодильная установка камеры корректно?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'oq', 20, 'Работает ли пульт управления без ошибок?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'oq' AND `equipmentType` = 'chamber' AND `text` = 'Работает ли пульт управления без ошибок?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'oq', 30, 'Реагирует ли система на изменение уставки температуры?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'oq' AND `equipmentType` = 'chamber' AND `text` = 'Реагирует ли система на изменение уставки температуры?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'oq', 40, 'Корректно ли работает индикация на дисплее (температура, режимы)?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'oq' AND `equipmentType` = 'chamber' AND `text` = 'Корректно ли работает индикация на дисплее (температура, режимы)?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'oq', 50, 'Работают ли вентиляторы и обеспечивается ли циркуляция воздуха внутри камеры?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'oq' AND `equipmentType` = 'chamber' AND `text` = 'Работают ли вентиляторы и обеспечивается ли циркуляция воздуха внутри камеры?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'oq', 60, 'Срабатывает ли сигнализация при отклонении температуры от установленных границ?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'oq' AND `equipmentType` = 'chamber' AND `text` = 'Срабатывает ли сигнализация при отклонении температуры от установленных границ?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'oq', 70, 'Срабатывает ли сигнализация открытой двери (если предусмотрена)?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'oq' AND `equipmentType` = 'chamber' AND `text` = 'Срабатывает ли сигнализация открытой двери (если предусмотрена)?');
--> statement-breakpoint
INSERT INTO `questionTemplates` (`stage`, `ord`, `text`, `isDefault`, `companyId`, `equipmentType`, `equipmentKind`) SELECT 'oq', 80, 'Отсутствуют ли посторонние шумы/вибрации во время работы холодильной установки?', 1, NULL, 'chamber', NULL WHERE NOT EXISTS (SELECT 1 FROM `questionTemplates` WHERE `stage` = 'oq' AND `equipmentType` = 'chamber' AND `text` = 'Отсутствуют ли посторонние шумы/вибрации во время работы холодильной установки?');
